version: '3.2'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    tty: true
    container_name: ${COMPOSE_PROJECT_NAME}_app
    hostname: app
    working_dir: /var/www/html
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - ./:/var/www/html:cached
      - ./:/var/run/php-fpm/
      - ./docker/config/xdebug.ini:/etc/php-7.4.d/15-xdebug.ini
    links:
      - database
  nginx:
    image: nginx:1.19.0
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    tty: true
    expose:
      - "80"
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./:/var/www/html:cached
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/config/conf.d/:/etc/nginx/conf.d/
      - ./docker/logs:/var/log/nginx/
    depends_on:
      - app

  # The Database
  database:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_db
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=app_db"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    expose:
      - "3306"
    restart: unless-stopped
    ports:
      - ${DB_PORT_H}:3306
  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpadmin
    restart: unless-stopped
    ports:
      - "${PHP_MYADMIN_PORT}:80"
    environment:
      PMA_HOST: database
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PMADB: ${DB_DATABASE}
  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    volumes:
      - ./docker/data/redis:/data
    ports:
      - "${REDIS_PORT_H}:6379"
  worker:
    build:
        context: docker/worker
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}_worker
    volumes:
      - ./:/src
      - ./docker/worker/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro
      - ./docker/worker/supervisord.d:/etc/supervisord.d
    depends_on:
      - database
  
  mailcatcher:
    restart: unless-stopped
    image: dockage/mailcatcher:0.7.1
    container_name: ${COMPOSE_PROJECT_NAME}_mailcatcher
    ports:
      - "${MAIL_PORT_H1}:1080"
      - "${MAIL_PORT_H2}:1025"

  